# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - main: ./cmd/myip
    binary: myip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Version }}'
  replacements:
    darwin: macos
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
